final List<String> categoryList = [
  "Programming",
  "Web Development",
  "Data Science",
  "Machine Learning",
  "Artificial Intelligence",
  "Mobile App Development",
  "Game Development",
  "Graphic Design",
  "UI/UX Design",
  "Digital Marketing",
  "Social Media Marketing",
  "Content Writing",
  "Copywriting",
  "SEO (Search Engine Optimization)",
  "SEM (Search Engine Marketing)",
  "Email Marketing",
  "Affiliate Marketing",
  "E-commerce",
  "Entrepreneurship",
  "Business Management",
  "Project Management",
  "Financial Accounting",
  "Investment Banking",
  "Cryptocurrency",
  "Stock Trading",
  "Real Estate Investing",
  "Personal Finance",
  "Photography",
  "Videography",
  "Photo Editing",
  "Video Editing",
  "Animation",
  "Music Production",
  "Voice Acting",
  "Creative Writing",
  "Screenwriting",
  "Blogging",
  "Podcasting",
  "Public Speaking",
  "Mindfulness and Meditation",
  "Yoga",
  "Fitness and Nutrition",
  "Cooking and Baking",
  "Language Learning (e.g., Spanish, French, Chinese)",
  "Music Theory",
  "Art History",
  "Interior Design",
  "Fashion Design",
  "Gardening and Horticulture",
  "DIY Crafts",
  "Knitting and Crocheting",
  "Personal Development",
  "Time Management",
  "Leadership Skills",
  "Negotiation Skills",
  "Emotional Intelligence",
  "Career Development",
  "Human Resources",
  "Psychology",
  "Philosophy",
  "History",
  "Astronomy",
  "Environmental Science",
  "Physics",
  "Biology",
  "Chemistry",
  "Mathematics",
  "Literature",
  "Film Studies",
  "Sociology",
  "Political Science",
  "Law and Legal Studies",
  "Health and Wellness Coaching",
  "Child Psychology",
  "Parenting Skills",
  "Relationship and Marriage Counseling",
  "Public Relations",
  "Cybersecurity",
  "Ethical Hacking",
  "Artificial Intelligence in Healthcare"
];
