// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKzWpGRL11K034IBVTW7g56-XTg6e_Fm0',
    appId: '1:771836921251:web:5aa42dd9b1a50e1ee98616',
    messagingSenderId: '771836921251',
    projectId: 'education-app-b5aed',
    authDomain: 'education-app-b5aed.firebaseapp.com',
    storageBucket: 'education-app-b5aed.appspot.com',
    measurementId: 'G-M3X7981JKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGFMAhWG2lDZSEaUAuFR0oRp8JOfxmcHM',
    appId: '1:771836921251:android:2697b9fdbf9cb1fde98616',
    messagingSenderId: '771836921251',
    projectId: 'education-app-b5aed',
    storageBucket: 'education-app-b5aed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUnHnZCPVlrLVaDQjTm2bahCh-LcdINgY',
    appId: '1:771836921251:ios:a842a440b85e40c0e98616',
    messagingSenderId: '771836921251',
    projectId: 'education-app-b5aed',
    storageBucket: 'education-app-b5aed.appspot.com',
    androidClientId:
        '771836921251-b0kln0o3ok07bq2i46sqeqns4mmpbspr.apps.googleusercontent.com',
    iosClientId:
        '771836921251-3qujf1kqcbm6ecrc8tumfaegr96u7ar5.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationFlutterWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUnHnZCPVlrLVaDQjTm2bahCh-LcdINgY',
    appId: '1:771836921251:ios:61a47b17c33ba7fbe98616',
    messagingSenderId: '771836921251',
    projectId: 'education-app-b5aed',
    storageBucket: 'education-app-b5aed.appspot.com',
    androidClientId:
        '771836921251-b0kln0o3ok07bq2i46sqeqns4mmpbspr.apps.googleusercontent.com',
    iosClientId:
        '771836921251-bh6fa3t1qr9upjpg35g3btgi69iartgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationFlutterWeb.RunnerTests',
  );
}
